version: '3.3'

services:
  app:
    container_name: 'app'
    build: .
    volumes:
      - ./src:/app
      - node_modules:/app/node_modules
    ports:
      - 7000:7000
    environment:
      - PORT=7000
    command: npm start
    tty: true
volumes:
  node_modules:
