version: '3.3'

services:
  app:
    container_name: 'app'
    build: .
    volumes:
      - ./src:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    command: npm run dev
    tty: true
volumes:
  node_modules:
